title: Tawer
description: Tawer の 博客
author: Tawer
avatar: /logo.png
email: admin@mail.tawertwtc.xyz
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
gitalk:
  enable: true
  github_id: tawer-blog # 你的Github ID/用户名
  repo: pinglun # 评论存放的仓库名称，可以是Github Page(username.github.io)所在的仓库或者另建一个仓库
  client_id: Ov23liNdm6yqxwqFq3hH # 前面拿到的Client ID
  client_secret: 05e6cc0c60044822d17b5ee33aecca1a783b120c # 前面拿到的Client secret


# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - 
    - 
    - 
google_site_verification: 
lang: cn
